spring.datasource.url=jdbc:postgresql://dpg-d7ihp4faqgkc739ueb50-a:5432/boleto_dnib
spring.datasource.username=boleto_dnib_user
spring.datasource.password=DCIbHbegz1XuAWvxHouSpezqWOLfSDy1

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true